export const safetyModelConfig = {
  metadata: {
    modelVersion: "dse-v1.0.0",
    configVersion: "safety-config-v1.0.0",
    status: "approved",
    effectiveFrom: "2026-07-14",
    rationale: "Transparent MVP simulation coefficients approved in docs/safety-model.md",
    limitations: [
      "Not calibrated to accident labels",
      "Not a medical fatigue model",
      "For deterministic plan comparison only",
    ],
  },
  budget: {
    initial: 100,
    breachThreshold: 30,
    supportThreshold: 45,
    cautionThreshold: 60,
  },
  forecast: {
    intervalMinutes: 5,
    horizonMinutes: 120,
  },
  normalization: {
    continuousWorkFreeMinutes: 120,
    continuousWorkRangeMinutes: 240,
    shiftFreeMinutes: 360,
    shiftRangeMinutes: 240,
    remainingStops: 50,
    remainingWeightKg: 250,
    stairStops: 20,
    atRiskTimeWindows: 10,
    stopWeightKg: 20,
    floorWithoutElevator: 9,
    rainfallMmPerHour: 20,
    snowfallCmPerHour: 3,
    heatStartCelsius: 28,
    heatRangeCelsius: 10,
    coldStartCelsius: 5,
    coldRangeCelsius: 15,
    visibilityStartMeters: 1_000,
    visibilityRangeMeters: 800,
    uphillGradePct: 12,
  },
  weights: {
    driver: {
      base: 2,
      continuousWork: 6,
      shiftDuration: 4,
      optionalState: 3,
    },
    task: {
      base: 1,
      remainingStops: 2.5,
      remainingWeight: 2,
      stairs: 2.5,
      timePressure: 1.5,
    },
    route: {
      base: 0.5,
      slope: 2.5,
      narrowRoad: 2,
      incident: 2,
      unfamiliar: 1.5,
      night: 1,
      serviceParking: 2,
    },
    weather: {
      rain: 3,
      snow: 4,
      heat: 3,
      cold: 2,
      lowVisibility: 2,
    },
    interaction: {
      rainSlope: 2,
      rainNarrow: 1.5,
      heatStairs: 2,
      nightUnfamiliar: 1.5,
    },
    stopEvent: {
      base: 0.1,
      weight: 0.35,
      floorWithoutElevator: 0.35,
      parking: 0.2,
    },
  },
  recovery: {
    freeMinutes: 5,
    effectiveMinutesCap: 25,
    pointsPerEffectiveMinute: 0.9,
    qualityFactors: {
      LOW: 0.5,
      UNKNOWN: 0.75,
      MEDIUM: 0.75,
      HIGH: 1,
    },
  },
  confidence: {
    demoPenalty: 25,
    directInitialBudgetPenalty: 10,
    horizonPenalties: [
      { afterMinutes: 90, penalty: 15 },
      { afterMinutes: 60, penalty: 10 },
      { afterMinutes: 30, penalty: 5 },
    ],
  },
  nightWindow: {
    startsAtHour: 22,
    endsAtHour: 6,
  },
} as const;

export type SafetyModelConfig = typeof safetyModelConfig;
